version: '3'
services:
  cassandra_single:
    image: cassandra:latest
    container_name: cass_single
    environment:
      CASSANDRA_SEEDS: "cassandra_single"
      CASSANDRA_CLUSTER_NAME: "CassSingle"
    ports:
      - "9052:9042"
