version: '3'
services:
  cassandra_1:
    image: cassandra:latest
    container_name: cass_cont1
    environment:
      CASSANDRA_SEEDS: "cassandra_1,cassandra_2,cassandra_3"
      CASSANDRA_CLUSTER_NAME: "CassCluster"
    networks:
      - cassandra-net
    ports:
      - "9042:9042"
    volumes:
      - ./conf_cass_1/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml

          
  cassandra_2:
    image: cassandra:latest
    container_name: cass_cont2
    environment:
      CASSANDRA_SEEDS: "cassandra_1,cassandra_2,cassandra_3"
      CASSANDRA_CLUSTER_NAME: "CassCluster"
    networks:
      - cassandra-net
    ports:
      - "9043:9042"
    volumes:
      - ./conf_cass_2/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml
    depends_on:
      cassandra_1:
        condition: service_started 


  cassandra_3:
    image: cassandra:latest
    container_name: cass_cont3
    environment:
      CASSANDRA_SEEDS: "cassandra_1,cassandra_2,cassandra_3"
      CASSANDRA_CLUSTER_NAME: "CassCluster"
    networks:
      - cassandra-net
    ports:
      - "9044:9042"  
    volumes:
      - ./conf_cass_3/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml
    depends_on:
      cassandra_2:
        condition: service_started

  # cassandra_4:
  #   image: cassandra:latest
  #   container_name: cass_cont4
  #   environment:
  #     CASSANDRA_SEEDS: "cassandra_1,cassandra_2,cassandra_3,cassandra_4,cassandra_5"
  #     CASSANDRA_CLUSTER_NAME: "CassCluster"
  #   networks:
  #     - cassandra-net
  #   ports:
  #     - "9045:9042"
  #   volumes:
  #     - ./conf_cass_4/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml
  #   depends_on:
  #     cassandra_3:
  #       condition: service_started

  # cassandra_5:
  #   image: cassandra:latest
  #   container_name: cass_cont5
  #   environment:
  #     CASSANDRA_SEEDS: "cassandra_1,cassandra_2,cassandra_3,cassandra_4,cassandra_5"
  #     CASSANDRA_CLUSTER_NAME: "CassCluster"
  #   networks:
  #     - cassandra-net
  #   ports:
  #     - "9046:9042"
  #   volumes:
  #     - ./conf_cass_5/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml
  #   depends_on:
  #     cassandra_4:
  #       condition: service_started

networks:
  cassandra-net:
    driver: bridge
